#!/usr/bin/env python3
#
# contact: righttoprivacy@tutanota.com
#
#
# RELATED REPOSITORY/PROTECTION/Blog: 
# https://www.buymeacoffee.com/politictech
# https://github.com/righttoprivacy/mactrack
# https://gitlab.com/Aresesi/wipri - WiPri metadata/mac/privacy protection
# See README for more information;
#
# My solution for preventing this from identifying you + step by step install: 
# https://www.buymeacoffee.com/politictech/mactrack-howto-use-it-identify-masked-burglars-strangers-outside-your-home
#
# My Linux/FOSS/Privacy Videos/Files :
# https://odysee.com/$/invite/@RTP:9
# https://tube.tchncs.de/video-channels/privacy__tech_tips
#
# You may need to use pip3 to install the following:
# scapy, yawigle, OuiLookup
#
# * Be sure to set your wifi card for monitor mode first *
#

from scapy.all import *
from yawigle import client
from OuiLookup import OuiLookup
import sys
import time
from colorama import Fore, Back, Style

# Sniffing the client for ssid

# logfile default is visitor.log; feel free to change;
logFile = open('visitor.log','a')
logo = '''

'##::::'##::::'###:::::'######::'########:'########:::::'###:::::'######::'##:::'##:
 ###::'###:::'## ##:::'##... ##:... ##..:: ##.... ##:::'## ##:::'##... ##: ##::'##::
 ####'####::'##:. ##:: ##:::..::::: ##:::: ##:::: ##::'##:. ##:: ##:::..:: ##:'##:::
 ## ### ##:'##:::. ##: ##:::::::::: ##:::: ########::'##:::. ##: ##::::::: #####::::
 ##. #: ##: #########: ##:::::::::: ##:::: ##.. ##::: #########: ##::::::: ##. ##:::
 ##:.:: ##: ##.... ##: ##::: ##:::: ##:::: ##::. ##:: ##.... ##: ##::: ##: ##:. ##::
 ##:::: ##: ##:::: ##:. ######::::: ##:::: ##:::. ##: ##:::: ##:. ######:: ##::. ##:
..:::::..::..:::::..:::......::::::..:::::..:::::..::..:::::..:::......:::..::::..::

'''

print(logo)

print(Fore.BLUE + "\n______________________________________________\n")
print(Fore.RED + "MACTRACK: RIGHTTOPRIVACY@TUTANOTA.COM\n")
print(Fore.BLUE + "______________________________________________\n")

def ssidprobes(pkt) :
        if pkt.haslayer(Dot11) :
                if pkt.type == 0 and pkt.subtype == 4 :
                        client = str(pkt.addr2)
                        ssid = ({pkt.info.decode('UTF-16')})
                        print(Back.BLACK + Fore.WHITE + "SSID Probes: ", client, '--->', ssid)
                        print(Back.BLACK + Fore.WHITE + "Client: ", OuiLookup().query(client))
                        print(Fore.BLUE + "\n______________________________________________\n")
                        
# ***  Change wlan0 to your wifi card 
while True:
        sniff(iface = "wlan0", prn = ssidprobes)

# Below we search wiggle for ssid location
# *** If you just want to monitor clients mac/brand -> SSID packets, 
# you don't need to worry about wigle API below ***
# Add your API account info in the brackets below for access to wigle:
        c = client('AIDinsertYoursHere', 'InsertYourNumberHere') # get API access insert here
        netname = input(Back.BLACK + Fore.WHITE + "Which SSID: ")
        nets = c.network.search(ssid=netname)
        print(Fore.YELLOW + "\n")
        for i in nets:
                print(i, str("\n"))
                logFile.write(str(i) + "\n\n")
        #logFile.write(str(i))
        print(Fore.RED + "SEARCH COMPLETE.\n")
        input(Fore.WHITE + "Press [Enter] To Return To Probe Watching:")
        logFile.close()
